language: android
jdk:
  - oraclejdk8
  - oraclejdk7

sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-23

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew build connectedCheck
  - ./gradlew projectReport
  - ./gradlew test
  - ./gradlew testDebugUnitTestCoverage coveralls


after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

#language: java
#jdk:
#  - oraclejdk8
#  - oraclejdk7
#
#sudo: false
#env:
#  - TERM=dumb
#
#before_install:
#  - chmod +x gradlew
#
#install:
#  - ./gradlew assemble
#
#script:
#  - ./gradlew check
#
#after_success:
#  - ./gradlew testDebugUnitTestCoverage coveralls
#
#before_cache:
#  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/
