language: android
jdk:
  - oraclejdk8

sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'

before_install:
  - unset $ANDROID_NDK_HOME
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew projectReport
  - ./gradlew test
  # Coverage
  - mkdir -p ./build/reports/jacoco/test/
  - ./gradlew jacocoTestReport
  - cp -f ./library/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml ./build/reports/jacoco/test/jacocoTestReport.xml
  - ls -la ./build/reports/jacoco/test/
  - ./gradlew coveralls

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
